version: "3"
services:
  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
        
  r3:
    container_name: r3
    image: r3
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis